server:
  servlet:
    context-path: /eshop
  port: 8080
spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        use_sql_comments=true:
